// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type Book struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Author      *Author `json:"author"`
	Description string  `json:"description"`
}

type BookInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	AuthorID    string `json:"authorID"`
}
